### ISSUE TITLE
Getting error message when try and run programme 

### ISSUE THREAD

**Issue by Denisnow99** [jimradford/superputty#690] opened 2018-02-25 20:01 UTC
"There was an error checking for updates - Please try again later."
I use Windows 10 OS

**Comment by dtruebin** [comment] 2018-02-27 13:33
This is a dupe of #689.

**Comment by jimradford** [comment] 2018-03-01 17:47
Duplicate of issue #689 Please see that issue for progress on this issue

**Closed by jimradford** 2018-03-01 17:47 UTC
