### ISSUE TITLE
Windows opens in new window if teamviewer is active

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#419] opened 2015-05-08 16:54 UTC
```
What steps will reproduce the problem?
1. Start teamviewer (v 9.0.26297)
2. Start superputty (v 1.4.0.4
3. Start an ssh putty session

The new putty session will start in a new window instead of in a new tab.
```

Original issue reported on code.google.com by `benjamin...@gmail.com` on 5 Mar 2014 at 8:02

**Comment by jimradford** [comment] 2015-09-25 19:52
Duplicate of Issue #309

**Closed by jimradford** 2015-09-25 19:52 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
