### ISSUE TITLE
Error during update check

### ISSUE THREAD

**Issue by randarp** [jimradford/superputty#692] opened 2018-03-01 13:36 UTC
For about a week now, every time I open up SuperPuTTY, I get the following error:

_Error during update check
There was an error while checking for updates. Please try again later._

I turned logging on, but there isn't any indicator of what the problem is. No errors logged.

2018-03-01 08:32:21,193 [1] INFO  SuperPutty.SuperPuTTY - Initialized
2018-03-01 08:32:21,381 [1] DEBUG SuperPutty.SuperPuTTY - STATUS: Ready
2018-03-01 08:32:21,381 [1] INFO  SuperPutty.frmSuperPutty - Checking for updates
2018-03-01 08:32:21,381 [1] INFO  SuperPutty.frmSuperPutty - Checking for application update
2018-03-01 08:32:21,432 [1] INFO  SuperPutty.Utils.FormUtils - Restoring form position and state.  position={X=3124,Y=407,Width=647,Height=989}, state=Maximized
2018-03-01 08:32:21,433 [1] INFO  SuperPutty.Utils.TabSwitcher - Initialing new strategy: Visual: Left-to-Right, Top-to-Bottom
2018-03-01 08:32:21,438 [1] DEBUG SuperPutty.frmSuperPutty - [461514] Activated

I'm not behind a proxy or anything like that, but have had problems connecting to IPs that change frequently, such as AWS Elastic Load Balancers. But I can't figure out from the source what URL it uses to update.

**Comment by Javaru** [comment] 2018-03-01 17:01
I have the same issue. But for me SuperPuTTY then locks up with the dreaded "SuperPuTTY is not responding" error. I am behind a proxy. I will test on my home PC which is not behind a proxy to see if I get the same behavior.

**Comment by jimradford** [comment] 2018-03-01 17:46
Duplicate of issue #689 Please see that issue for progress on this issue

**Closed by jimradford** 2018-03-01 17:46 UTC
