### ISSUE TITLE
Bug in the version number 1.4.10 -> 1.4.0.10

### ISSUE THREAD

**Issue by juleindev** [jimradford/superputty#857] opened 2021-12-20 15:04 UTC
Superputty request upgrade a each start

![image](https://user-images.githubusercontent.com/22550738/146787940-fd4ad4be-0116-415f-b909-398b1fe2d728.png)

![image](https://user-images.githubusercontent.com/22550738/146788151-5e46f242-43d9-419c-aace-c76f54e51220.png)

Version download 1.4.10 but the version in the archive file is 1.4.0.10.

**Comment by jimradford** [comment] 2021-12-20 15:08
Duplicate of Issue #853

**Comment by jimradford** [comment] 2023-01-29 17:09
Fixed in Release 1.5.0.0

**Closed by jimradford** 2023-01-29 17:09 UTC
