### ISSUE TITLE
Windows update killed Superputty (think) 

### ISSUE THREAD

**Issue by whirichardson** [jimradford/superputty#782] opened 2020-02-19 18:46 UTC
**Describe the bug**
After a Window 7 update Superputty begins to start then after a minute it's back to icon. part of the Windows log in my user Appdata folders is below.  

System.ComponentModel.Win32Exception: The parameter is incorrect
   at System.Drawing.Icon.Initialize(Int32 width, Int32 height)

**To Reproduce**
1. Go to Windows 
2. Click on Superputty
3. Scroll down to NA
4. See error NA

**Expected behavior**
Superputty launches with all my store sessions

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I had IT support "help" me but they couldn't get it working, updated .NET and reinstalled.

**Comment by blajoie** [comment] 2020-02-22 18:24
Same issue here, updated win 7 last night, and now superputty does not open.  This looks to be terminal, time to find a new terminal :/

**Comment by blajoie** [comment] 2020-02-22 18:27
```
2020-02-22 10:26:35,665 [1] INFO  SuperPutty.Program - Starting
2020-02-22 10:26:35,679 [1] INFO  SuperPutty.SuperPuTTY - Initializing.  Version=1.4.0.8, UserSettings=C:\Users\blajoie\SuperPuTTY.settings, SettingsFolder=C:\Users\blajoie\Documents\SuperPuTTY
2020-02-22 10:26:35,696 [1] WARN  SuperPutty.SuperPuTTY - theme directory not found, no images loaded. dir=C:\windows\system32\themes\default\icons
2020-02-22 10:26:35,704 [1] INFO  SuperPutty.SuperPuTTY - Loaded 0 layouts
2020-02-22 10:26:35,707 [1] INFO  SuperPutty.SuperPuTTY - Loading all sessions.  file=C:\Users\blajoie\Documents\SuperPuTTY\Sessions.XML
2020-02-22 10:26:35,828 [1] INFO  SuperPutty.Data.SessionData - Loaded 10 sessions from C:\Users\blajoie\Documents\SuperPuTTY\Sessions.XML
2020-02-22 10:26:35,829 [1] INFO  SuperPutty.SuperPuTTY - Added Session, id=asus
2020-02-22 10:26:35,829 [1] INFO  SuperPutty.SuperPuTTY - Added Session, id=ukch-prd-brln
2020-02-22 10:26:35,829 [1] INFO  SuperPutty.SuperPuTTY - Added Session, id=usfc-prd-brln
2020-02-22 10:26:35,829 [1] INFO  SuperPutty.SuperPuTTY - Added Session, id=ussd-dev-cldg01
2020-02-22 10:26:35,829 [1] INFO  SuperPutty.SuperPuTTY - Added Session, id=ussd-dev-lnbl01
2020-02-22 10:26:35,829 [1] INFO  SuperPutty.SuperPuTTY - Added Session, id=ussd-dev-lnbl02
2020-02-22 10:26:35,830 [1] INFO  SuperPutty.SuperPuTTY - Added Session, id=ussd-rnd
2020-02-22 10:26:35,830 [1] INFO  SuperPutty.SuperPuTTY - Added Session, id=ussd-sccs
2020-02-22 10:26:35,830 [1] INFO  SuperPutty.SuperPuTTY - Added Session, id=ussd-services
2020-02-22 10:26:35,830 [1] INFO  SuperPutty.SuperPuTTY - Added Session, id=ussd-tst-drgn37
2020-02-22 10:26:35,831 [1] INFO  SuperPutty.SuperPuTTY - Starting with default layout, <Auto Restore>
2020-02-22 10:26:35,833 [1] INFO  SuperPutty.Utils.SingleInstanceHelper - Registered IpcChannel and Service: [ipc://SuperPuTTY/SingleInstance]
2020-02-22 10:26:35,835 [1] INFO  SuperPutty.SuperPuTTY - Initialized
2020-02-22 10:26:36,045 [1] ERROR SuperPutty.Program - Error in Main
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ComponentModel.Win32Exception: The parameter is incorrect
   at System.Drawing.Icon.Initialize(Int32 width, Int32 height)
   at System.Drawing.Icon..ctor(SerializationInfo info, StreamingContext context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle._SerializationInvoke(Object target, SignatureStruct& declaringTypeSig, SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at SuperPutty.frmSuperPutty.InitializeComponent()
   at SuperPutty.frmSuperPutty..ctor()
   at SuperPutty.Program.Main(String[] args)
2020-02-22 10:26:36,050 [1] INFO  SuperPutty.Program - Shutdown
```

**Comment by blajoie** [comment] 2020-02-24 16:04
p.s. for any others affected.  A windows restore does fix this issue.

**Comment by garagan** [comment] 2020-02-25 13:16
I had the same thing when this update was installed

[https://support.microsoft.com/en-ca/help/4537813/windows-7-update-kb4537813](https://support.microsoft.com/en-ca/help/4537813/windows-7-update-kb4537813)

**Comment by garagan** [comment] 2020-02-25 13:27
> 
> 
> I had the same thing when this update was installed
> 
> https://support.microsoft.com/en-ca/help/4537813/windows-7-update-kb4537813

Just found this reference in the MSDN forums, seems to be an issue with an icon definition in the resx file for the frmSuperPutty form (if I read this correctly)

[https://social.msdn.microsoft.com/Forums/en-US/b7cdcdc6-522f-4ea3-9764-cbaa9715d595/kb4537820-causes-systemcomponentmodelwin32exception-in-net-framework-systemdrawingicon-for?forum=clr](https://social.msdn.microsoft.com/Forums/en-US/b7cdcdc6-522f-4ea3-9764-cbaa9715d595/kb4537820-causes-systemcomponentmodelwin32exception-in-net-framework-systemdrawingicon-for?forum=clr)

**Comment by waukeerules** [comment] 2020-03-05 15:26
Has anyone found a way to launch SuperPuTTY with the patch installed?

**Comment by blajoie** [comment] 2020-03-05 17:38
I think this is DOA... RIP superPutty :/

**Comment by blajoie** [comment] 2020-03-05 17:38
Nope.  I think this is DOA... RIP superPutty.

**Comment by jimradford** [comment] 2020-03-05 20:11
Is the trouble you are having launcing SuperPutty or is it opening up new terminals? 

I am pretty sure I can fix this with a little help from you guys. What patch / update are you referring to? 

Jim

**Comment by fvinluan** [comment] 2020-03-05 21:00
I have having the same issue. It happens when launching SuperPutty. However, I tried deleting the SuperPuTTY.settings file and it will open the window to setup putty etc. After that SuperPutty will not work.

**Comment by blajoie** [comment] 2020-03-05 21:00
The issue is with opening super-putty.  See above for the error message.
https://github.com/jimradford/superputty/issues/782#issuecomment-589984648
Something to do with a .NET update ?

I have tried 1.4.0.8 & 1.4.0.9 - both have the same issue.

**Comment by garagan** [comment] 2020-03-06 03:07
> 
> 
> Is the trouble you are having launcing SuperPutty or is it opening up new terminals?
> 
> I am pretty sure I can fix this with a little help from you guys. What patch / update are you referring to?
> 
> Jim

Hey Jim,

I posted the update link and a reference to the possible issue above:

https://github.com/jimradford/superputty/issues/782#issuecomment-590861263

**Comment by prabuvnc** [comment] 2020-03-07 18:48
Any way to launch SuperPUTTY without uninstalling that patch? I am facing the same issue.

**Comment by eckertd** [comment] 2020-03-09 19:04
> Any way to launch SuperPUTTY without uninstalling that patch? I am facing the same issue.

Same situation here; patched Win7 not able to start SuperPuTTY with the same messages in the log file as mentioned above. My neighbor is running SuperPuTTY on Windows 10 with no issue, so that may be an option for you (your mileage may vary).

**Comment by eurodba** [comment] 2020-03-10 01:07
Gents, same issue, vote +1 - after latest Windows Update on top of Windows 7 (on OS or on .NET Framework - not sure, but can find, if needed) - SuperPutty (**v.1.4.0.4**) failed to start. Log file **%TEMP%\SuperPutty_[date]_[time].log** shows same error as in above posted Comment #782:

```
System.Reflection.TargetInvocationException:
Exception has been thrown by the target of an invocation.
---> System.ComponentModel.Win32Exception: The parameter is incorrect
```

Trying to delete all existing conf. files:

```
%APP_FOLDER%\SuperPutty.exe.config
%APP_FOLDER%\Settings\Layout\Sessions.XML
%USERPROFILE%\SuperPutty\Sessions.XML
%USERPROFILE%\SuperPutty.settings
```

... result is the same, i.e. no difference. In logilfe (in **%TEMP%** folder) I can see messages that particular conf. file not found - during load of **Layout** or during load of **Sessions** - but on overall situation that does not have any effect - at the end same errror **"The parameter is incorrect"**.

Maybe one interesting finding, even not important within current investigation - "just to know": attempt to delete **%USERPROFILE%\Sessions.XML** file - during start of application, SuperPutty.exe detects that **Sessions.XML** does not exists - and prints into log following confusing message:

```
Exception has been thrown by the target of invocation.
< ... cut ... >
The operation completed successfully.
```

I.e. in one row - **"Exception encountered"** and **"Completed successfully"**. How to interpret such behavior - don't know. Subsequent starts of SuperPutty.exe - continued **"standard"** error, i.e. **"The parameter is incorrect"**.

**Comment by dvenus** [comment] 2020-03-10 23:36
Hi! Same issue here. One thing I see is that SuperPutty says it has loaded 38 icons from the icons folder -- however there are only 36 files in the folder. So unless some files have multiple icons that looks like an error.

thanks!

**Comment by bashlibrary** [comment] 2020-03-11 08:01
Hi.
We have the same situation here, some users are not able to use SuperPuTTY any more.
I stressed several Windows 7 based test environments to figure out, what makes the difference between the one where it still works and where not.
All machines have this Win7 update, but most of the users can still use SuperPuTTY without any problem, but some not.

**Comment by max5962** [comment] 2020-03-11 17:29
Same here, after upgrading my laptop at work.

**Comment by CharlSka** [comment] 2020-03-12 08:36
+ 10 :)
We are several co-worker having the same issue

**Comment by rgprasanna** [comment] 2020-03-16 01:07
started observing same issue....is anyone working on it?

**Comment by aheyes** [comment] 2020-03-16 08:35
I'm experiencing the same issue as are handful of my colleagues who use the application regularly.  Happy to provide any information that might aid in finding a fix.  Seems to be the same scenario as many other commenters, after installing a .NET update in Win7 64-bit machines.

**Comment by max5962** [comment] 2020-03-20 08:51
someone is working on it ? 
thanks.

**Comment by garagan** [comment] 2020-03-20 17:17
Hey there,
OK....MSFT might have actually fixed something.  My machine updated with a number of patches last night and today, when I started SuperPutty, it came up!  One of the patches was called:

[March 10, 2020—KB4541500 (Security-only update)](https://support.microsoft.com/en-ca/help/4541500/windows-7-update-kb4541500)

This is the only one that matches the one that seemed to cause the issue that I mentioned above.  Has anyone else installed the latest patches from Microsoft and if so, does SuperPutty work again for them?

Thanks,
Sean

**Comment by PaulDubar** [comment] 2020-03-24 00:46
Same here...boo-hoo. Struggled through all the steps everyone else tried and now ended up here.
Thanks MSFT!
I cannot install the security update myself - its a company laptop.
Will have to wait for them to catch up with the latest update.

Friends laugh at me when I tell them I disable all updates because they are more trouble than they are worth! I wait for everyone else to be the guinea pigs! In this case I had no choice.

[SuperPuTTY.20200324_112728.log](https://github.com/jimradford/superputty/files/4372552/SuperPuTTY.20200324_112728.log)

**Comment by blajoie** [comment] 2020-03-24 01:16
@jimradford - can you take a look at this PR?  Is this the fix? 
https://github.com/jimradford/superputty/pull/786

**Comment by eckertd** [comment] 2020-04-13 19:08
> Hey there,
> OK....MSFT might have actually fixed something. My machine updated with a number of patches last night and today, when I started SuperPutty, it came up! One of the patches was called:
> 
> [March 10, 2020—KB4541500 (Security-only update)](https://support.microsoft.com/en-ca/help/4541500/windows-7-update-kb4541500)
> 
> This is the only one that matches the one that seemed to cause the issue that I mentioned above. Has anyone else installed the latest patches from Microsoft and if so, does SuperPutty work again for them?
> 
> Thanks,
> Sean

This may be the one that fixed it. Checked my PC, which received this update on 3/26, and I can happily report SuperPuTTY works again!

**Comment by jimradford** [comment] 2020-04-16 15:36
> 
> 
> @jimradford - can you take a look at this PR? Is this the fix?
> #786

Egads! yes, I somehow missed this.

**Comment by dariyappa** [comment] 2020-04-22 11:08
getting "couldn't agree key exchange algorithm" Error using SUperPutty. Any fix for this.

**Comment by jimradford** [comment] 2020-04-22 13:31
@dariyappa Please open a new issue as what you mention does not seem to be related. (Hint: Your server is probably not supporting any of the ciphers in putty. 1) can you connect to that host with putty all by itself? 2) try upgrading to putty 0.65 or later)

**Closed by jimradford** 2020-04-22 13:31 UTC

**Comment by abdullahsurati** [comment] 2021-02-09 11:30
I might be facing this in Windows 10 as well. More details in #815 .
Do you think it is the same issue?
