### ISSUE TITLE
ctrl tab and ctrl shift tab is not working in 1.4.0.6

### ISSUE THREAD

**Issue by mskumaran** [jimradford/superputty#521] opened 2015-06-19 14:54 UTC
ctrl tab and ctrl shift tab is not working in 1.4.0.6 getting too slow. Please fix it. thanks a lot your great support,

**Comment by jimradford** [comment] 2015-09-20 04:09
I am unable to reproduce, be sure the SuperPutty application is in focus when you press the keystrokes maybe?

Closing Issue: Cannot reproduce. Feel free to reopen this issue if you have any additional information to add.

**Closed by jimradford** 2015-09-20 04:09 UTC

**Comment by waukeerules** [comment] 2015-09-20 04:57
I might be able to reproduce this bug. Every once in awhile all shortcut keys will be locked as if the window is out of focus. To resolve the issue I've simply closed the application and re-opened it. I'll get back to you on this one.

**Comment by jimradford** [comment] 2015-09-20 16:37
@waukeerules Thanks, if we can recreate it I'll be glad to fix!

**Comment by waukeerules** [comment] 2015-09-20 21:50
I'm having a hard time recreating the issue. But I have noticed the issue tends to pop up when doing something that causes SuperPuTTY to lose focus. When accepting the ssh key for example, occasionally this window is pushed behind SuperPuTTY. To bring the window forward to accept the key I've had to manually minimize and maximize the window from the taskbar. At this point I have to close SuperPuTTY and re-open it to bring my shortcut keys back to life. There isn't any debug output when the shortcut keys are unavailable during this time. Do you have any ideas you'd like me to try to get better information?

note: I am using KiTTY while I troubleshoot the issue.

**Comment by ktmdms1** [comment] 2016-01-08 15:08
I have this problem in 1.4.0.8 as well.  I have a shortcut of Ctrl+Alt+D to duplicate sessions that goes flaky sometimes and every time I hit the d key in a session I get a duplicate session created.  And then the other shortcuts won't work either.  It almost seems like the session takes control of the key strokes or something for awhile.

**Comment by wenzel-k** [comment] 2016-01-17 10:54
Same problem here. Version 1.4.0.8.
I noticed when i am trying to switch tabs (Ctrl+tab) and nothing happens and i click with the mouse for example on the menu button 'Tools' nothing happens on the first click. Only on the second the drop down menu opens. Like others mentioned, it seems that SuperPutty lost focus.

Best regards

**Comment by varun0410** [comment] 2017-05-01 02:10
Hello, 
I am also facing the same issue, not able to switch between the tabs. Please let me know which information you will be needing to find the issue, i will share.
Thanks

**Comment by varun0410** [comment] 2017-05-01 02:19
2017-05-01 12:15:26,256 [1] INFO  SuperPutty.Utils.KeyEventWindowActivator - [16978008] Activating Main Window - current=(C:\Program Files (x86)\Notepad++\notepad++.exe)
2017-05-01 12:15:26,261 [1] INFO  SuperPutty.ApplicationPanel - [16978008] ReFocusPuTTY - puttyTab=<server_name>, caller=WinEventProc-FG, AltTab=False, result=True
2017-05-01 12:15:26,263 [1] DEBUG SuperPutty.frmSuperPutty - [11470648] Activated
2017-05-01 12:15:26,663 [1] WARN  SuperPutty.ctlPuttyPanel - Unable to SetFocusToChildApplication, <server_name>

these are the logs from %TEMP%\SuperPutty.<DATE>.log . Super putty version 1.4.0.8

**Comment by SK2815** [comment] 2017-06-28 07:17
I am facing the similar problem with the version 1.4.0.8
Earlier i was using windows 7 32 bit, never found this problem in that configuration. But now when i am using win 10 64 bit, i could see the problem from the day 1.
Any recovery of the bug ?
