### ISSUE TITLE
SuperPuTTY 1.4..0.7 crashes and won't pin to taskbar!

### ISSUE THREAD

**Issue by Bob3001** [jimradford/superputty#559] opened 2015-10-23 08:16 UTC
Running on Win Server 2008 R2. Versions before 1.4..0.7 seem to work fine. Used the zipped version.

![superputty_crash](https://cloud.githubusercontent.com/assets/15260905/10687649/ef4b4ef2-796e-11e5-9644-85669d7636d1.JPG)

**Comment by jimradford** [comment] 2015-10-23 14:41
Hi @Bob3001 Thanks for the report. I believe this is due to enabling the update checker by default but not having proper error checking for when something does not go right. I've fixed this in the trunk source but it has not been officially released in binary form. Test builds are available and are generally quite stable (They are the versions I personally use between releases)

Duplicate of Issue #557 

The easy fix until 1.4.0.8 is released would be to uninstall SuperPuTTY and install a test build from here: https://ci.appveyor.com/api/buildjobs/2u08yxev6k981mom/artifacts/SuperPuttyInstaller/bin/Debug/SuperPuttySetup.msi

Thanks

**Comment by masskonfuzion** [comment] 2015-10-23 15:28
Hey Jim,

Any chance you could release the portable version of that test build?  I have the same issue as @Bob3001, but I don't have admin privileges on the box where I do my SuperPuTTYing.


Thanks for keeping up SuperPuTTY! The world needs it.

**Comment by jimradford** [comment] 2015-10-23 15:31
@masskonfuzion Grab the EXE from the artifacts directory and it should be a drop-in replacement for the current exe: https://ci.appveyor.com/project/jimradford/superputty/build/artifacts

Let me know if that fixes the issue for you.

**Comment by masskonfuzion** [comment] 2015-10-23 15:35
It worked! Thanks!

**Comment by Bob3001** [comment] 2015-10-24 06:03
Thanks for the quick reply. I'll wait for 1.4.0.8 as I have no issues with 1.4.0.6. If I should run into trouble I know how to fix it. 

Thanks for the great work!

**Closed** 2015-10-25 22:48 UTC
Labels: duplicate
