### ISSUE TITLE
scp does not use key

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#47] opened 2015-05-08 16:50 UTC
```
0. Load session data of a putty session using an SSH key
1. Double-click on the session in the right-hand side column: ssh connection 
works OK.
2. This time, right-click on the session in the right-hand side column.
3. Click on File Transfer
4. Popup asks for user/password


At step4, instead of asking for credentials, the pscp.exe program should use 
the same key as used by the putty.exe program
```

Original issue reported on code.google.com by `igor.ros...@gmail.com` on 10 Apr 2012 at 2:56

**Comment by jimradford** [comment] 2015-09-25 19:59
Duplicate of Issue #546

**Closed by jimradford** 2015-09-25 19:59 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
