### ISSUE TITLE
1.4.0.10 Control Panel - Programs Version is incorrect

### ISSUE THREAD

**Issue by michaelehart** [jimradford/superputty#861] opened 2022-01-18 23:13 UTC
We upgraded several Windows 10 and 11 users with SuperPuttySetup-1.4.10.msi but the Control Panel - Programs and Features shows version 1.4.0.9.  It's an issue for us because the software we use to monitor installed versions uses the Control Panel version.
![image](https://user-images.githubusercontent.com/24458403/150032926-8fe71a9a-65f1-48f8-af64-dc1e603edd37.png)
The version is correct inside SuperPutty Help About
![image](https://user-images.githubusercontent.com/24458403/150033362-04ee6cec-5e79-420c-9f32-c72655fd113b.png)
Thank You for writing and maintaining this awesome software!

**Comment by SanjayMadhavan** [comment] 2022-01-19 06:42
I get notified of an updated version 1.4.10 being available even after installing 1.4.0.10.
is the version 1.4.0.10 or is it 1.4.10?

The latest release page also has this same conflict. The version numbers listed are 1.4.0.10 and 1.4.10 in two different places

**Comment by mariuszjedrzejewski** [comment] 2022-02-18 14:14
I believe that is typo in 1.4.10 (lack of '0' on third pos). Other tags are 1.4.0.9, 1.4.0.8 and so on.

**Comment by dofuuz** [comment] 2022-04-27 02:04
Duplicate of Issue #853, #857

Anyway, I think next version should be 1.4.11 or 1.4.11.0, to avoid confusion with version sorting.

**Comment by rustyjarz** [comment] 2022-07-06 23:34
> Just updated to this release and this is a bit annoying and i think ppl will turn off search for updates if this isn't fixed, will there be any new release out soon?

I've switched off check for new versions as this is annoying.

**Comment by jocker-il** [comment] 2022-07-19 13:20
I have the same issue - will also turn off version checking

 - please update when this is fixed


> Duplicate of Issue #853, #857
> 
> Anyway, I think next version should be 1.4.11 or 1.4.11.0, to avoid confusion with version sorting.

I agree - the third decimal should reflect the minor version hotfix (the versioning traditionally goes xx.yy.zz where as XX is the main version - major changes, YY is minor version - medium level changes not requiring a fresh install or setup changes and ZZ is usually for hotfixes when when the minor update had to be fixed due to small bugs like this one

 - but, to each his own, it's not a requirement...

**Comment by jimradford** [comment] 2023-01-29 17:08
Fixed in Release 1.5.0.0

**Closed by jimradford** 2023-01-29 17:08 UTC
