### ISSUE TITLE
Mintty.exe: Process has exited, so the requested information is not available.

### ISSUE THREAD

**Issue by neuromancerxi** [jimradford/superputty#528] opened 2015-08-11 20:21 UTC
Mintty 2.1.4 (x86_64-pc-cygwin)
Error on launch (but spawns separate window): Invalid Operation Error - Process has exited, so the requested information is not available.

![ocr](https://cloud.githubusercontent.com/assets/3996176/9209518/c6ac3ab4-402b-11e5-8068-eee46719ed84.jpg)

**Comment by jimradford** [comment] 2015-09-20 03:58
Thanks for the Bug report. Unhandled exceptions should never be thrown.
@neuromancerxi can you do me a favor and try to recreate this exceptions being thrown with debug enabled? Also what version of SuperPutty are you running?

**Comment by neuromancerxi** [comment] 2015-09-20 04:29
Superputty 1.4.0.6

Do you have directions that I can follow to provide you with greater detail? I didn't see any options in the menus or notes on running SupperPutty with debugging enabled.

Logs:

2015-09-19 21:13:33,423 DEBUG        frmSuperPutty - [263126] Activated
2015-09-19 21:13:33,429 INFO           TabSwitcher - Cleaning up old strategy: Visual: Left-to-Right, Top-to-Bottom
2015-09-19 21:13:33,430 INFO           TabSwitcher - Initialing new strategy: Visual: Left-to-Right, Top-to-Bottom
2015-09-19 21:13:33,432 DEBUG           SuperPuTTY - STATUS: Ready
2015-09-19 21:13:33,516 INFO      ApplicationPanel - [15795654] ReFocusPuTTY - puttyTab=neuro@UbuntuVM: ~, caller=SHELLHOOK, result=True
2015-09-19 21:13:37,745 DEBUG        frmSuperPutty - [263126] Activated
2015-09-19 21:13:37,956 INFO            SuperPuTTY - Opening putty session, id=Z_Other/Cygwin
2015-09-19 21:13:37,958 INFO        PuttyStartInfo - Putty Args: '-'
2015-09-19 21:13:38,159 WARN      ApplicationPanel - Unable to get handle for process on first try.  Polling 10 s for handle.                                                                                                                       
2015-09-19 21:13:49,218 DEBUG        frmSuperPutty - [263126] Activated                                                                                                                                                                             
2015-09-19 21:13:49,283 ERROR              Program - Application_ThreadException                                                                                                                                                                    
2015-09-19 21:13:51,567 DEBUG        frmSuperPutty - [263126] Activated                                                                                                                                                                             
2015-09-19 21:13:51,653 INFO      ApplicationPanel - [15795654] ReFocusPuTTY - puttyTab=neuro@UbuntuVM: ~, caller=SHELLHOOK, result=True                                                                                                            
2015-09-19 21:13:54,020 DEBUG        frmSuperPutty - [263126] Activated

**Comment by jimradford** [comment] 2015-09-20 16:40
@neuromancerxi Are you compiling from Source or using precombiled Binaries?

**Comment by neuromancerxi** [comment] 2015-09-20 17:58
Pre-compiled binaries for both.

**Comment by jimradford** [comment] 2015-09-25 04:07
@neuromancerxi  will you grab the latest build from here https://ci.appveyor.com/api/buildjobs/c5p29ikv73i3xca3/artifacts/SuperPuttyInstaller/bin/Debug/SuperPuttySetup.msi It has debugging information enabled so an exception should provide better details of where this is ocurring.

**Comment by jimradford** [comment] 2015-09-25 16:13
Going to Bump this until 1.4.0.8 since it does not appear to affect the bulk of the userbase.

**Comment by neuromancerxi** [comment] 2015-09-28 18:40
With the debug build and now mintty 2.1.5 (x86_64-pc-cygwin):

![mintty](https://cloud.githubusercontent.com/assets/3996176/10145019/8edb18ec-65d5-11e5-97a7-5016b2b83f08.png)

**Comment by jimradford** [comment] 2015-09-29 04:47
@neuromancerxi can you provide steps to reproduce? 
Thanks!

**Comment by atlasloewenherz** [comment] 2015-09-29 08:03
$ mintty.exe --version
Ignoring malformed option ':'.
mintty 2.1.5 (x86_64-pc-cygwin)
(C) 2013/2015 Andy Koppe / Thomas Wolff
License GPLv3+: GNU GPL version 3 or later
There is no warranty, to the extent permitted by law.

# Windows 7 Enterprise SP1 64BIT OS

tried "reinstalling" re unzipping more than 4 times ( even after cygwin reinstall)

still get the same problem ( see screenshot )

![supperputty bug](https://cloud.githubusercontent.com/assets/3721197/10158274/2c6fc880-6691-11e5-8f4a-d7f714f1e319.png)

**Comment by neuromancerxi** [comment] 2015-09-30 15:30
1. Download latest Cygwin Installer: https://cygwin.com/setup-x86_64.exe
2. Install Cygwin
2a. I added only the "bind-util" package to the defaults
3. Either Extract Superputty from zip or install via debug msi installer
3a. Installed to C:\Program Files (x86)\SuperPutty
4. Install Putty 0.65, defaults
5. Run SuperPutty as "Administrator"
6. Configure Super Putty by pointing it to putty, pscp and mintty
7. Create a new Session
7a. ![mintty2](https://cloud.githubusercontent.com/assets/3996176/10197602/578f34c6-674d-11e5-861c-769dfb03dcd1.png)
8. Launch

**Comment by jimradford** [comment] 2015-10-01 05:17
@neuromancerxi Thanks for the update. I'll work on this when I am back from travels. Around October 15th.

**Comment by joeyhub** [comment] 2015-10-01 10:18
You can work around this in the meantime if you set up cygwin with sshd.

**Comment by dklawson** [comment] 2015-10-03 01:10
I also had this issue, but was able to do some troubleshooting this evening. The issue is caused by the current version of mintty.exe distributed with cygwin. In the new version, if mintty thinks that it wasn't started from a terminal, it will fork itself and then exit. Since superputty doesn't notice this, it tries to wait on the initial mintty process, which has already exited.

Fortunately, there is a mintty config setting to disable this behavior. Just add "daemonize=false" to the .minttyrc file in your cygwin home dir.

**Comment by neuromancerxi** [comment] 2015-10-06 13:10
@dklawson Thank you, your workaround solved my issue for the short term.

**Comment by jimradford** [comment] 2015-10-26 20:27
The Exception being thrown I believe has been fixed. The handling of mintty will need to be addressed in documentation unless there is a commandline option that can be passed to mintty to "fix" the daemonizing behavior.

**Comment by dklawson** [comment] 2015-10-26 20:37
I think --nodaemon should work as a command line option.

**Comment by jimradford** [comment] 2015-10-26 20:40
@dklawson does that affect previous versions of mintty if --nodaemon is passed on the command line?

**Comment by dklawson** [comment] 2015-10-26 21:05
Looks like the default for the 'daemon' feature was changed from *off* (enabled via --daemon) to *on* (disabled via --nodaemon), starting in v2.1.4 of mintty ([commit 4e68399](https://github.com/mintty/mintty/commit/4e6839985d72bca4c50541d1a493f82ddb5c37d4)). It will return an error for invalid options, so there would need to be some version checking added.

**Comment by jimradford** [comment] 2015-10-26 21:29
It appears you set options with -o <option>=<value> so -o daemonize=false works with the current 2.1.4 -o foo=bar still allows the shell to start properly it seems and is invalid. I'll commit the fix and see if I can find someone still using the old version to test.

**Closed** 2015-10-26 21:33 UTC
Labels: Confirmed-Bug, Priority-Medium
