### ISSUE TITLE
SCP cannot list files / directories owned by used with a period

### ISSUE THREAD

**Issue by ppslim** [jimradford/superputty#533] opened 2015-08-30 17:50 UTC
Due to use of LDAP for central system, user and group management, all user credentials come from a central location.

Our uids take the form firstname.lastname. As such, files and directories, including our home directories are owned by this user including a dot in the middle. Groups are departmental and do not contain dots (at present, there is noting to prevent this in the future).

Any files or folder owned by a user with a dot in the username does not show up in the SCP window.

Unlike #531 which reports "Unable to open", SCP does not do this on this occasion. It correctly lists the parent directory ".." as it is owned by root, but the current directory "." and contents are not displayed.

An example of this is in my home directory, I create a file as root

`$ sudo touch aaaa`

This file will render on SCP login, but no other entries.

**Comment by jimradford** [comment] 2015-09-03 19:52
Thanks for the report. I'll see if I can setup an account locally to mimic your environment and try to reproduce.

**Comment by jimradford** [comment] 2015-09-19 20:19
Fix for this has been comitted to master. Will be included in 1.4.0.7 or if you want to test a build artifact was produced: https://ci.appveyor.com/api/buildjobs/jf0esyf7wmaxpp77/artifacts/SuperPuttyInstaller/bin/Debug/SuperPuttySetup.msi

**Comment by ppslim** [comment] 2015-09-19 20:45
Much appreciated.

I didn't know it was regexp.

Is there any reason you are not using something such as [[:graph:]]+ to handle capture of that?

Just using the first capture attempt from PscpTransfer.cs
https://regex101.com/r/oD5zW6/1

**Comment by jimradford** [comment] 2015-09-19 21:24
In All Honesty, it was simply because that was probably 8 years ago when it was initially implemented. And the file transfer tool was just a quick  thing to see "if" I could do it. I personally rarely use it but I also see the benefit of maintaining and improving it where I can. I am no regexp guru relying on much trial and error for anything too complex. I'll look into any benefits of using [[:graph:]]. 

Thanks for the input and the report.

**Comment by jimradford** [comment] 2015-09-24 03:46
need to re-evaluate this as I've found another issue #440 that looks related but with a '-' instead of a '.'.

**Closed** 2015-09-25 04:04 UTC
Labels: bug
